import React, { useEffect, useMemo, useState } from 'react';
import { Film, Filter, RefreshCw, Sparkles, TrendingUp } from 'lucide-react';
import { Navbar } from './components/Navbar';
import { MovieCard } from './components/MovieCard';
import { BoxOfficeSection } from './components/BoxOfficeSection';
import { NewsSection } from './components/NewsSection';
import { TeluguHistorySection } from './components/TeluguHistorySection';
import { BookmarksSection } from './components/BookmarksSection';
import { WpConfigModal } from './components/WpConfigModal';
import { Footer } from './components/Footer';
import { ArticleDetail } from './components/ArticleDetail';
import { ArticleRecord, Language, NavTab, SiteContent, WordPressConfig } from './types';
import { allArticles } from './articleData';
import { fallbackData } from './data/initialData';
import { fetchSiteContent, getStoredWpConfig, saveWpConfig } from './services/contentFetcher';

const BOOKMARKS_STORAGE_KEY = 'reelnreal_saved_bookmarks';
const categoryLabels: Record<string, string> = {'/movie-updates':'Movie Updates','/national-news':'National News','/local-news':'Local News','/andhra-pradesh':'Andhra Pradesh News','/politics':'Politics','/sports':'Sports','/business':'Business','/technology':'Technology','/entertainment':'Entertainment','/lifestyle':'Lifestyle','/trending':'Trending'};

export default function App() {
  const [path, setPath] = useState(window.location.pathname || '/'); const [activeTab, setActiveTab] = useState<NavTab>('news'); const [language, setLanguage] = useState<Language>('en'); const [searchQuery, setSearchQuery] = useState(''); const [selectedCategory, setSelectedCategory] = useState('all'); const [siteContent, setSiteContent] = useState<SiteContent>(fallbackData); const [loading, setLoading] = useState(true); const [wpConfig, setWpConfig] = useState<WordPressConfig>(getStoredWpConfig()); const [isWpModalOpen, setIsWpModalOpen] = useState(false); const [bookmarks, setBookmarks] = useState<any[]>(() => { try { return JSON.parse(localStorage.getItem(BOOKMARKS_STORAGE_KEY) || '[]'); } catch { return []; } });
  const navigate = (next: string) => { const target = next.startsWith('/') ? next : `/${next}`; if (target !== path) { window.history.pushState({}, '', target); setPath(target); } else window.scrollTo({top:0, behavior:'smooth'}); };
  useEffect(() => { const onPop = () => setPath(window.location.pathname || '/'); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  useEffect(() => { localStorage.setItem(BOOKMARKS_STORAGE_KEY, JSON.stringify(bookmarks)); }, [bookmarks]);
  useEffect(() => { (async () => { setLoading(true); try { setSiteContent(await fetchSiteContent(wpConfig)); } catch { setSiteContent(fallbackData); } finally { setLoading(false); } })(); }, [wpConfig.contentSource, wpConfig.baseUrl]);
  const articles = useMemo(() => allArticles(siteContent), [siteContent]);
  const articleId = path.startsWith('/article/') ? decodeURIComponent(path.split('/article/')[1]) : '';
  const selectedArticle = articleId ? articles.find(article => article.id === articleId) : undefined;
  const searchResults = searchQuery.trim() ? articles.filter(a => `${a.title} ${a.category} ${a.excerpt}`.toLowerCase().includes(searchQuery.toLowerCase())) : [];
  const categoryArticles = path !== '/' ? articles.filter(a => a.categorySlug === path.slice(1)) : [];
  const toggleBookmark = (item: any) => { const key = item.id || item.title || item.headline; setBookmarks(prev => prev.some(b => (b.id || b.title || b.headline) === key) ? prev.filter(b => (b.id || b.title || b.headline) !== key) : [...prev, item]); };
  const isBookmarked = (key: any) => bookmarks.some(item => (item.id || item.title || item.headline) === key);
  const openArticle = (article: ArticleRecord) => navigate(`/article/${encodeURIComponent(article.id)}`);
  const renderCards = (items: ArticleRecord[]) => <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{items.map(article => <article key={article.id} onClick={() => openArticle(article)} className="group bg-zinc-900/80 border border-zinc-800 rounded-2xl overflow-hidden cursor-pointer hover:border-amber-500/60 transition-all"><div className="aspect-[16/9] bg-zinc-950">{article.image ? <img src={article.image} alt={article.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform" loading="lazy" onError={e => { e.currentTarget.style.display='none'; }} /> : <div className="h-full flex items-center justify-center text-zinc-600 text-xs">Image unavailable</div>}</div><div className="p-5"><span className="text-[10px] font-black uppercase tracking-widest text-amber-400">{article.category}</span><h3 className="font-serif-display text-lg font-bold mt-2 group-hover:text-amber-400">{article.title}</h3><p className="text-sm text-zinc-400 mt-2 line-clamp-2">{article.excerpt}</p><div className="text-xs text-zinc-500 mt-4">{article.publishedAt}</div></div></article>)}</div>;
  const home = <div className="space-y-10"><section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-red-950/70 via-zinc-900 to-zinc-950 p-7 sm:p-12 border border-red-500/20"><div className="relative z-10 max-w-3xl"><span className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-red-300"><Sparkles className="w-4 h-4" /> Breaking News & Entertainment</span><h1 className="font-serif-display text-3xl sm:text-6xl font-black mt-4 leading-tight">The stories shaping your world and screen.</h1><p className="text-zinc-400 mt-4 max-w-2xl">{language === 'te' ? 'రాజకీయాలు, స్థానిక వార్తలు, సినిమాలు మరియు వినోదం.' : 'Independent coverage of national news, local stories, Telugu cinema, sports and culture.'}</p></div></section>{searchResults.length > 0 && <section><SectionTitle title="Search results" /><div className="mb-5 text-sm text-zinc-400">{searchResults.length} matching articles</div>{renderCards(searchResults)}</section>}<section><SectionTitle title="Latest updates" /><div className="grid lg:grid-cols-2 gap-6"><NewsSection politicalNews={siteContent.politicalNews || []} localNews={siteContent.localNews || []} language={language} onToggleBookmark={toggleBookmark} isBookmarked={isBookmarked} onSelectArticle={openArticle} /></div></section><section><SectionTitle title="Movie Updates" /><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{siteContent.movies.slice(0,4).map(movie => <MovieCard key={String(movie.id || movie.title)} movie={movie} language={language} isBookmarked={isBookmarked(movie.id || movie.title)} onToggleBookmark={toggleBookmark} onSelectMovie={() => {}} onSelectArticle={openArticle} />)}</div></section></div>;
  let content: React.ReactNode;
  if (selectedArticle) content = <ArticleDetail article={selectedArticle} related={articles.filter(a => a.id !== selectedArticle.id && a.categorySlug === selectedArticle.categorySlug)} language={language} onOpenArticle={openArticle} onNavigate={navigate} />;
  else if (path === '/') content = home;
  else if (categoryLabels[path]) content = <div className="space-y-6"><div><span className="text-xs uppercase tracking-widest text-amber-400 font-black">Reel N Real</span><h1 className="font-serif-display text-4xl sm:text-5xl font-black mt-2">{categoryLabels[path]}</h1><p className="text-zinc-400 mt-2">Latest stories from the {categoryLabels[path].toLowerCase()} desk.</p></div>{categoryArticles.length ? renderCards(categoryArticles) : <div className="rounded-2xl border border-zinc-800 bg-zinc-900/60 p-12 text-center text-zinc-400">No published stories in this category yet.</div>}</div>;
  else if (activeTab === 'movies') content = <div className="space-y-6"><h1 className="font-serif-display text-4xl font-black">Movie Updates</h1><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">{siteContent.movies.map(movie => <MovieCard key={String(movie.id || movie.title)} movie={movie} language={language} isBookmarked={isBookmarked(movie.id || movie.title)} onToggleBookmark={toggleBookmark} onSelectMovie={() => {}} onSelectArticle={openArticle} />)}</div></div>;
  else if (activeTab === 'boxoffice') content = <BoxOfficeSection items={siteContent.boxOfficeLive} top5={siteContent.boxOfficeTop5} updates={siteContent.boxOfficeUpdates} language={language} />;
  else if (activeTab === 'history') content = <TeluguHistorySection historyItems={siteContent.teluguFilmHistory} language={language} onSelectMovie={() => {}} />;
  else content = <BookmarksSection bookmarks={bookmarks} language={language} onRemoveBookmark={toggleBookmark} onSelectMovie={() => {}} onClearAll={() => setBookmarks([])} />;
  return <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col"><Navbar activeTab={activeTab} setActiveTab={setActiveTab} language={language} setLanguage={setLanguage} searchQuery={searchQuery} setSearchQuery={setSearchQuery} bookmarksCount={bookmarks.length} onOpenSettings={() => setIsWpModalOpen(true)} wpConfig={wpConfig} onNavigate={navigate} currentPath={path} /><main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8">{loading ? <div className="min-h-[45vh] flex items-center justify-center"><RefreshCw className="w-8 h-8 text-amber-500 animate-spin" /></div> : content}</main><Footer language={language} setActiveTab={setActiveTab} />{isWpModalOpen && <WpConfigModal config={wpConfig} language={language} onSave={config => { setWpConfig(config); saveWpConfig(config); }} onClose={() => setIsWpModalOpen(false)} />}</div>;
}
const SectionTitle = ({title}:{title:string}) => <h2 className="font-serif-display text-3xl font-black border-l-4 border-amber-500 pl-4">{title}</h2>;
